name: Build GDWave (3DS)

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-3ds
  cancel-in-progress: true

jobs:
  build-3DS:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@v4

      - name: Build .3dsx
        run: |
          cd 3ds
          make

      - name: Upload GDWave .3dsx
        uses: actions/upload-artifact@v4
        with:
          name: GDWave-3dsx
          path: 3ds/build/GDWave3DS.3dsx
